## Global Variabel
#@BaseUrl = https://pam-2026-p5-ifs18005-be.delcom.org:8080
#@BaseUrl = http://127.0.0.1:8000

@BaseUrl = https://pam-2026-ifs23013-proyek1-be.weslyambaritaa.fun:8080/

### ---------------------------------------
## Auth
### ---------------------------------------

### Melakukan pendaftaran
# @name PostRegister
POST {{BaseUrl}}/auth/register
Content-Type: application/json

{
  "name": "Tester",
  "username": "tester",
  "password": "tester"
}

### Masuk ke layanan
# @name PostLogin
POST {{BaseUrl}}/auth/login
Content-Type: application/json

{
  "username": "tester",
  "password": "tester"
}

> {%
    client.global.set("authToken", response.body.data.authToken);
    client.global.set("refreshToken", response.body.data.refreshToken);
%}

### Keluar dari layanan (skip run)
# @name PostLogout
POST {{BaseUrl}}/auth/logout
Content-Type: application/json

{
  "authToken": "{{authToken}}"
}

### Masuk ke layanan
# @name PostRefreshToken
POST {{BaseUrl}}/auth/refresh-token
Content-Type: application/json

{
  "authToken": "{{authToken}}",
  "refreshToken": "{{refreshToken}}"
}

> {%
    client.global.set("authToken", response.body.data.authToken);
    client.global.set("refreshToken", response.body.data.refreshToken);
%}

### ---------------------------------------
## Users
### ---------------------------------------

### Mengambil informasi akun
# @name GetUserMe
GET {{BaseUrl}}/users/me
Authorization: Bearer {{authToken}}
Content-Type: application/json

> {%
    client.global.set("userId", response.body.data.user.id);
%}

### Mengubah informasi akun
# @name PutUserMe
PUT {{BaseUrl}}/users/me
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "name": "Tester Update",
  "username": "tester"
}

### Mengubah kata sandi akun
# @name PutUserMePassword
PUT {{BaseUrl}}/users/me/password
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "newPassword": "tester",
  "password": "tester"
}

### Mengubah photo profile
# @name PutUserMePhoto
PUT {{BaseUrl}}/users/me/photo
Authorization: Bearer {{authToken}}
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="example.png"
Content-Type: image/png

< ./uploads/examples/me.png
--WebAppBoundary--

### Mengambil data tumbuhan berdasarkan id-nya
@userId = 00ed9d33-61b0-48b7-a32a-6510af028731

# @name GetMyPhoto
GET {{BaseUrl}}/images/users/{{userId}}
Authorization: Bearer {{authToken}}
Content-Type: application/json

### ---------------------------------------
## Todos
### ---------------------------------------

### Mengambil semua data todo user saat ini
# @name GetTodos
GET {{BaseUrl}}/todos?search=
Authorization: Bearer {{authToken}}
Content-Type: application/json

### Menambahkan todo
# @name PostTodos
POST {{BaseUrl}}/todos
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "title": "Judul Todo",
  "description": "Deskripsi Todo"
}

> {%
    client.global.set("todoId", response.body.data.todoId);
%}

### Mengambil todo dengan id
# @name GetTodoById
GET {{BaseUrl}}/todos/{{todoId}}
Authorization: Bearer {{authToken}}
Content-Type: application/json

### Mengubah todo
# @name PutTodo
PUT {{BaseUrl}}/todos/{{todoId}}
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "title": "Judul Todo",
  "description": "Deskripsi Todo",
  "isDone": true
}

### Mengubah cover todo
# @name PutTodoCover
PUT {{BaseUrl}}/todos/{{todoId}}/cover
Authorization: Bearer {{authToken}}
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="example.png"
Content-Type: image/png

< ./uploads/examples/me.png
--WebAppBoundary--

### Mengambil cover todo
# @name GetTodoCover
GET {{BaseUrl}}/images/todos/{{todoId}}
Authorization: Bearer {{authToken}}
Content-Type: application/json

### Menghapus todo
# @name DeleteTodo
DELETE {{BaseUrl}}/todos/{{todoId}}
Authorization: Bearer {{authToken}}
Content-Type: application/json

### ---------------------------------------
## Foods (Canteen Del)
### ---------------------------------------

### Mengambil semua menu makanan
# @name GetFoods
GET {{BaseUrl}}/foods?search=
Authorization: Bearer {{authToken}}
Content-Type: application/json


### Menambahkan menu makanan
# @name PostFoods
POST {{BaseUrl}}/foods
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "name": "Nasi Goreng",
  "description": "Nasi goreng spesial dengan telur",
  "price": 15000,
  "category": "Makanan",
  "available": true
}

> {%
    client.global.set("foodId", response.body.data.foodId);
%}


### Mengambil menu makanan berdasarkan id
# @name GetFoodById
GET {{BaseUrl}}/foods/{{foodId}}
Authorization: Bearer {{authToken}}
Content-Type: application/json


### Mengubah menu makanan
# @name PutFood
PUT {{BaseUrl}}/foods/{{foodId}}
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "name": "Nasi Goreng Spesial",
  "description": "Nasi goreng dengan ayam dan telur",
  "price": 18000,
  "category": "Makanan",
  "available": true
}


### Upload gambar makanan
# @name PutFoodImage
PUT {{BaseUrl}}/foods/{{foodId}}/image
Authorization: Bearer {{authToken}}
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="food.png"
Content-Type: image/png

< ./uploads/examples/me.png
--WebAppBoundary--


### Mengambil gambar makanan
# @name GetFoodImage
GET {{BaseUrl}}/images/foods/{{foodId}}
Authorization: Bearer {{authToken}}
Content-Type: application/json


### Menghapus menu makanan
# @name DeleteFood
DELETE {{BaseUrl}}/foods/{{foodId}}
Authorization: Bearer {{authToken}}
Content-Type: application/json